class BooksColor {
  String booksName;
  bool booksColor;
  BooksColor(
    this.booksName,
    this.booksColor,
  );
}

List<BooksColor> allbooks = [
  BooksColor("Genesis", false),
  BooksColor("Exodus", false),
  BooksColor("Leviticus", false),
  BooksColor("Numbers", false),
  BooksColor("Deuteronomy", false),
  BooksColor("Joshua", false),
  BooksColor("Judges", false),
  BooksColor("Ruth", false),
  BooksColor("1 Samuel", false),
  BooksColor("2 Samuel", false),
  BooksColor("1 Kings", false),
  BooksColor("2 Kings", false),
  BooksColor("1 Chronicles", false),
  BooksColor("2 Chronicles", false),
  BooksColor("Ezra", false),
  BooksColor("Jeremiah", false),
  BooksColor("Lamentation", false),
  BooksColor("Ezekiel", false),
  BooksColor("Daniel", false),
  BooksColor("Hosea", false),
  BooksColor("Joel", false),
  BooksColor("Amos", false),
  BooksColor("Obadiah", false),
  BooksColor("Jonah", false),
  BooksColor("Micah", false),
  BooksColor("Nahum", false),
  BooksColor("Habakkuk", false),
  BooksColor("Zephaniah", false),
  BooksColor("Haggai", false),
  BooksColor("Zachariah", false),
  BooksColor("Malchi", false),
  // New Testament
  BooksColor("Matthew", true),
  BooksColor("Mark", true),
  BooksColor("Luke", true),
  BooksColor("John", true),
  BooksColor("Acts", true),
  BooksColor("Romans", true),
  BooksColor("1 Corinthians", true),
  BooksColor("2 Corinthians", true),
  BooksColor("Galatians", true),
  BooksColor("Ephesians", true),
  BooksColor("Philippians", true),
  BooksColor("Colossians", true),
  BooksColor("1 Thessalonians", true),
  BooksColor("2 Thessalonians", true),
  BooksColor("1 Timothy", true),
  BooksColor("2 Timothy", true),
  BooksColor("Titus", true),
  BooksColor("Philemon", true),
  BooksColor("Hebrews", true),
  BooksColor("James", true),
  BooksColor("1 Peter", true),
  BooksColor("1 Peter", true),
  BooksColor("1 John", true),
  BooksColor("2 John", true),
  BooksColor("3 John", true),
  BooksColor("Jude", true),
  BooksColor("Revelation", true),
];

List<String> bookChapters = [
  "50 Chapters",
  "10 Chapters",
  "25 Chapters",
  "5 Chapters",
  "50 Chapters",
  "10 Chapters",
  "25 Chapters",
  "5 Chapters",
];
List<String> selectChapters = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "20",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
  "27",
  "28",
  "29",
  "30",
  "31",
  "32",
  "33",
  "34",
  "35",
  "36",
  "37",
  "38",
  "39",
  "40",
  "41",
  "42",
  "43",
  "44",
  "45",
];
